Создал openapi.yaml
cement-hools/Auth_sprint_1 pull request #6
Opened 2023-02-08 09:39 UTC by cement-hools

2023-02-08 10:55 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/history:
Nit: Я вот думаю, может на это тоже пост запрос? Это вроде довольно персональные данные. Как я понял, с GET больше возможностей нахакать.

2023-02-08 10:56 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +paths:
Не хватает смены пароля из ТЗ

2023-02-08 10:58 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/roles:
Не хватает ручек для 

- назначить такому-то юзеру такую-то роль
- проверить что у такого-то юзера есть такая-то роль

2023-02-08 10:58 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/history:
как ты нахакаеешь, если это всего лишь id пользователя.
могу переделать, но мне кажется все через GET делают

2023-02-08 11:01 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +    LoginUserResponse:
По идее мы же хотим еще токен возвращать на логине?

2023-02-08 11:02 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
В ТЗ было вроде из всех *других* сеансов.
Плюс тут на входе нужен токен

2023-02-08 11:06 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +    ValidationError:
Вижу неконсистентность, но может ты мне расскажешь почему так выбрал.

Когда получаешь 200, там есть на верхнем уровне success, error, data.
Я бы ожидал что при ошибке будут такие же узлы на верхнем уровне, просто error будет заполнен, и success false и data пустое. Это касается схем всех ошибок.

2023-02-08 11:08 UTC, cement-hools commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
я подумал по user_id сможем завершить сеансы

2023-02-08 11:09 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - Role
Мне кажется для пользования этой апишкой тоже нужны токены авторизации. Ну или как-то явно громко пометить что это внутренняя апи и внешняя авторизация не нужна для нее, типа тока из локалки будем пускать) 
Хотя, что я такое говорю, из локалки несекьюрно пускать всех попало тоже)

2023-02-08 11:09 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/roles:
проверить роль можно получив все роли пользователя

2023-02-08 11:09 UTC, andrey-lepekhin requested changes
Очень круто что так быстро сделал, есть комментарии

2023-02-08 11:10 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
Да-да, у меня коммент именно про описание

2023-02-08 11:11 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/history:
Давай оставим, я специально пометил как придирку (Nit), настаивать не буду

2023-02-08 11:12 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/roles:
Ты прав, тогда только первая строка актуальна

2023-02-08 11:14 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
Хотя сорри, первая строка про описание, а вторая про необходимость авторизации.

Кстати, я так понял в апи это обычно делают через заголовки. Может так же и у нас сделаем, а не отдельным пармаетром?

2023-02-08 11:35 UTC, cement-hools commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
не когда так не делал. покажи пример

2023-02-08 11:37 UTC, cement-hools commented on schemas/openapi.yaml
> +    ValidationError:
по идеи так и должно быть. свагер делаю через фастапи. не знаю как там указать ошибочный респонс

2023-02-08 11:38 UTC, cement-hools commented on schemas/openapi.yaml
> +        - Role
из локалки пускают только админов, которые добавляют фильмы. 
так я понял теорию.
а они в джанго админ ходят

2023-02-08 15:41 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
https://stackoverflow.com/a/45471010/196171

https://swagger.io/docs/specification/authentication/bearer-authentication/

2023-02-08 15:45 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +    ValidationError:
Вот здесь можно вручную переписывать и смотреть https://editor.swagger.io/

Условно, можешь скопировать то, что ты уже сделал туда и вручную поправить текст, чтобы было как надо.

2023-02-08 15:46 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - Role
Опиши тогда пожалуйста где-то как пользователи будут получать авторизацию для испольования этих ручек

2023-02-08 18:20 UTC, cement-hools commented on schemas/openapi.yaml
> +      description: Выход пользователя из всех сеансов.
Добавил правила с авторизацией по токену на ручки

2023-02-08 18:21 UTC, cement-hools commented on schemas/openapi.yaml
> +        - Role
описал

2023-02-09 05:19 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - user_id
В других ручках для определения пользователя используется login. А почему тут именно user_id?

2023-02-09 05:22 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - refresh_token
Я пока не до конца понимаю как будет работать эта система, но на всякий случай подсвечу: тут точно рефреш токен на вход нужен? Я думал он нужен чтобы именно рефрешить. А для логаута нужен обычный токен.

Повторю, не знаю как это работает, это именно вопрос, не просьба что-то менять.

2023-02-09 05:27 UTC, cement-hools commented on schemas/openapi.yaml
> +        - refresh_token
я тоже не доконца понял, может и токен нужен.

2023-02-09 05:27 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/roles/add:
Вот тут непонятно. Судя по расположению ручки, ты как будто предполагаешь что юзер сам будут себе добавлять роль? 

Я думал добавление ролей это какая-то внутренняя логика, не доступная внешнемю юзеру. То есть часть второй апишки roles.

Или я не понимаю чего-то. Можешь поясинть?

2023-02-09 05:30 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/logout:
Тут кстати не нужна авторизация по токену?

2023-02-09 05:30 UTC, cement-hools commented on schemas/openapi.yaml
> +        - user_id
логин нужен чтобы залогинтеться, пользователь же не знает свой id.
а когда меняем пароль пользователь уже залогинен и может передать id для того чтобы легче было его найти в БД

2023-02-09 05:32 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - Role
Вижу ты в итоге их тоже под авторизацией токенами сделал, всё верно?

2023-02-09 05:34 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +        - user_id
И логин и юзер айди уникальны будут в таблице и на оба будут индексы скорее всего. 

То есть ускорения поиска БД не будет, а вот фронтедеру, который будет апишку реализовывать, нужно будет думать почему идентификатор пользователя в разных ручках разный.

2023-02-09 05:36 UTC, cement-hools commented on schemas/openapi.yaml
> +        - Role
да

2023-02-09 05:38 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/roles/add:
Не сам будет добавлять. но по restfull думаю так правильнее. есть юзер, его роли. и добавление

2023-02-09 05:40 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/logout:
нужна!

2023-02-09 05:44 UTC, andrey-lepekhin commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/roles/add:
В ТЗ наделение ролями это часть второй апишки и я сколнен согласиться.
Если унести эту часть в апишку ролей, то вся папка users будет доступна извне и это будет понятное разделение.

Можно сделать рестфул через ресурс роли, например, roles/{role_id}/add_user

2023-02-09 05:51 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/roles/add:
хорошо

2023-02-09 05:55 UTC, cement-hools commented on schemas/openapi.yaml
> +        - user_id
ну хорошо, сделаем логин. только фронтеру думаю все ровно, все ровно по документации будет писать

2023-02-10 07:22 UTC, cement-hools commented on schemas/openapi.yaml
> +        - user_id
сделал логин

2023-02-10 07:22 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/logout:
сделал

2023-02-10 07:43 UTC, cement-hools commented on schemas/openapi.yaml
> +  /api/v1/user/{user_id}/roles/add:
сделал

2023-02-10 10:35 UTC, andrey-lepekhin submitted a review, later dismissed

2023-02-10 17:33 UTC, andrey-lepekhin approved these changes

2023-02-11 05:17 UTC, merged